import { useFocusEffect, router } from "expo-router";
import { PackageOpen, Plus, Search } from "lucide-react-native";
import { useCallback, useMemo, useState } from "react";
import { Pressable, StyleSheet, Text, TextInput, View } from "react-native";

import { Button } from "@/src/components/ui/button"; import { Card } from "@/src/components/ui/card"; import { EmptyState } from "@/src/components/ui/empty-state"; import { Screen } from "@/src/components/ui/screen";
import { colors, radius, spacing } from "@/src/constants/theme"; import { useDatabaseReady } from "@/src/db/database-provider"; import { createProductRepository } from "@/src/db/repositories/product-repository"; import type { Product } from "@/src/types/domain"; import { formatCurrency } from "@/src/utils/currency"; import { isLowStock } from "@/src/utils/stock";
import { filterProducts, type ProductFilterMode } from "./product-filter";

export const InventoryScreen = () => {
  const { db } = useDatabaseReady(); const [products, setProducts] = useState<Product[]>([]); const [query, setQuery] = useState(""); const [mode, setMode] = useState<ProductFilterMode>("all");
  useFocusEffect(useCallback(() => { createProductRepository(db).list().then(setProducts); }, [db]));
  const visible = useMemo(() => filterProducts(products, query, mode), [products, query, mode]);
  return <Screen scroll style={styles.screen}><View style={styles.heading}><View><Text style={styles.title}>Inventory</Text><Text style={styles.body}>{products.filter((item) => item.isActive).length} active products</Text></View><Button label="Add product" onPress={() => router.push("/product/new")} /></View>
    <View style={styles.search}><Search color={colors.muted} size={20} /><TextInput value={query} onChangeText={setQuery} placeholder="Search name or SKU" placeholderTextColor={colors.muted} style={styles.searchInput} /></View>
    <View style={styles.filters}>{(["all", "low", "inactive"] as const).map((item) => <Pressable key={item} onPress={() => setMode(item)} style={[styles.filter, mode === item && styles.filterActive]}><Text style={[styles.filterText, mode === item && styles.filterTextActive]}>{item === "all" ? "All" : item === "low" ? "Low stock" : "Inactive"}</Text></Pressable>)}</View>
    {visible.length === 0 ? <EmptyState icon={PackageOpen} title="No products here" body="Add the first product or change the current filter." actionLabel="Add product" onAction={() => router.push("/product/new")} /> : visible.map((product) => <Pressable key={product.id} onPress={() => router.push(`/product/${product.id}`)}><Card style={styles.product}><View style={styles.flex}><Text style={styles.productName}>{product.name}</Text><Text style={styles.meta}>{product.sku || "No SKU"} · {formatCurrency(product.sellingPricePaise)}</Text></View><View style={styles.stock}><Text style={[styles.stockValue, isLowStock(product) && styles.low]}>{product.trackInventory ? product.stockQuantity : "—"}</Text><Text style={styles.meta}>{isLowStock(product) ? "Low stock" : "In stock"}</Text></View></Card></Pressable>)}
    <Pressable accessibilityLabel="Add product" onPress={() => router.push("/product/new")} style={styles.fab}><Plus color={colors.inverse} size={24} /></Pressable>
  </Screen>;
};
const styles = StyleSheet.create({ screen: { gap: spacing.md }, heading: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" }, title: { color: colors.text, fontSize: 32, fontWeight: "800" }, body: { color: colors.muted, fontSize: 14 }, search: { alignItems: "center", backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radius.md, borderWidth: 1, flexDirection: "row", gap: spacing.sm, paddingHorizontal: spacing.md }, searchInput: { color: colors.text, flex: 1, fontSize: 16, minHeight: 50 }, filters: { flexDirection: "row", gap: spacing.sm }, filter: { borderColor: colors.border, borderRadius: 999, borderWidth: 1, paddingHorizontal: spacing.md, paddingVertical: spacing.sm }, filterActive: { backgroundColor: colors.text, borderColor: colors.text }, filterText: { color: colors.text, fontWeight: "700" }, filterTextActive: { color: colors.inverse }, product: { alignItems: "center", flexDirection: "row", gap: spacing.md }, flex: { flex: 1 }, productName: { color: colors.text, fontSize: 17, fontWeight: "700" }, meta: { color: colors.muted, fontSize: 13, marginTop: spacing.xs }, stock: { alignItems: "flex-end" }, stockValue: { color: colors.text, fontSize: 20, fontWeight: "800" }, low: { color: colors.danger }, fab: { alignItems: "center", alignSelf: "flex-end", backgroundColor: colors.text, borderRadius: 28, height: 56, justifyContent: "center", width: 56 } });
